language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

matrix:
  include:
    - php: 5.5
      env: SYMFONY_VERSION='2.3.*'
    - php: 5.5
      env: SYMFONY_VERSION='2.5.*@dev'

before_script:
  - curl -s http://getcomposer.org/installer | php
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then php composer.phar require --no-update symfony/symfony=$SYMFONY_VERSION; fi;'
  - php composer.phar install --prefer-source
  - export PATH=./vendor/bin:$PATH

script:
  - vendor/bin/phpspec run --config phpspec.yml --format pretty
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml
  - behat -fprogress --strict